spring:
    profiles:
        active: default
    
    jpa.hibernate.ddl-auto: update
    datasource:
     url: jdbc:mysql://localhost:3306/campamento
     username: root
     password: admin
     driver-class-name: com.mysql.cj.jdbc.Driver
     hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
 
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level.org.hibernate.SQL: warn
  level: warn
server:
    port: 8080
urlCors: http://localhost:5173